import type { EmployeeData } from "@/components/employee-profile-hover"

// Mock employee data
export const employeeData: Record<string, EmployeeData> = {
  "Ahmet Demir": {
    id: "1",
    name: "Ahmet Demir",
    position: "Regional Manager",
    department: "Operations",
    company: "Isbank Russia",
    bio: "Experienced regional manager with expertise in banking operations and team leadership. Focused on expanding Isbank's presence in the Russian market.",
    email: "ahmet.demir@isbank.ru",
    linkedinUrl: "https://linkedin.com/in/ahmetdemir",
  },
  "Mehmet Yılmaz": {
    id: "2",
    name: "Mehmet Yılmaz",
    position: "CEO",
    department: "Executive",
    company: "Ziraat Bank Russia",
    bio: "Strategic leader with over 15 years of experience in international banking. Specializes in market expansion and digital transformation.",
    imageUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/employee1-YQnXnXQXXXXXXXXXXXXXXXXXXXXXXXX.jpg",
    email: "mehmet.yilmaz@ziraat.ru",
    linkedinUrl: "https://linkedin.com/in/mehmetyilmaz",
  },
  "Fatih Kaya": {
    id: "3",
    name: "Fatih Kaya",
    position: "Branch Manager",
    department: "Branch Operations",
    company: "Deniz Bank Russia",
    bio: "Branch operations expert with a focus on customer service excellence and team development. Led multiple successful branch expansions.",
    email: "fatih.kaya@denizbank.ru",
    linkedinUrl: "https://linkedin.com/in/fatihkaya",
  },
  "Selin Aksoy": {
    id: "4",
    name: "Selin Aksoy",
    position: "Marketing Director",
    department: "Marketing",
    company: "Beko Russia",
    bio: "Creative marketing professional with extensive experience in brand development and digital marketing strategies in the Russian market.",
    imageUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/employee2-YQnXnXQXXXXXXXXXXXXXXXXXXXXXXXX.jpg",
    email: "selin.aksoy@beko.ru",
    linkedinUrl: "https://linkedin.com/in/selinaksoy",
  },
  "Zeynep Yıldız": {
    id: "5",
    name: "Zeynep Yıldız",
    position: "Retail Manager",
    department: "Retail Operations",
    company: "Mavi Russia",
    bio: "Retail operations specialist with expertise in fashion retail management and customer experience optimization.",
    email: "zeynep.yildiz@mavi.ru",
    linkedinUrl: "https://linkedin.com/in/zeynepyildiz",
  },
  "Ali Demir": {
    id: "6",
    name: "Ali Demir",
    position: "Project Director",
    department: "Project Management",
    company: "Ruscam",
    bio: "Project management professional specializing in manufacturing operations and process optimization in the glass industry.",
    imageUrl: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/employee3-YQnXnXQXXXXXXXXXXXXXXXXXXXXXXXX.jpg",
    email: "ali.demir@ruscam.ru",
    linkedinUrl: "https://linkedin.com/in/alidemir",
  },
}

