"use client"
import { DollarSign, TrendingUp, ArrowDownRight, ArrowUpRight, HelpCircle } from "lucide-react"
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { formatCurrency } from "@/lib/utils"

interface CompanyFinancialsProps {
  investment?: number
  revenue?: number
  importVolume?: number
  exportVolume?: number
  language?: "en" | "tr" | "ru"
}

// Translations
const translations = {
  en: {
    financials: "Financials",
    investment: "Investment in Russia",
    revenue: "Annual Revenue",
    importVolume: "Import Volume",
    exportVolume: "Export Volume",
    investmentDesc: "Total capital investment made by the company in the Russian market",
    revenueDesc: "Total annual revenue generated by the company's operations in Russia",
    importDesc: "Total value of goods and services imported into Russia by the company",
    exportDesc: "Total value of goods and services exported from Russia by the company",
    noData: "No data available",
  },
  tr: {
    financials: "Finansal Bilgiler",
    investment: "Rusya'daki Yatırım",
    revenue: "Yıllık Ciro",
    importVolume: "İthalat Hacmi",
    exportVolume: "İhracat Hacmi",
    investmentDesc: "Şirketin Rusya pazarında yaptığı toplam sermaye yatırımı",
    revenueDesc: "Şirketin Rusya'daki operasyonlarından elde ettiği toplam yıllık gelir",
    importDesc: "Şirket tarafından Rusya'ya ithal edilen mal ve hizmetlerin toplam değeri",
    exportDesc: "Şirket tarafından Rusya'dan ihraç edilen mal ve hizmetlerin toplam değeri",
    noData: "Veri mevcut değil",
  },
  ru: {
    financials: "Финансы",
    investment: "Инвестиции в России",
    revenue: "Годовой доход",
    importVolume: "Объем импорта",
    exportVolume: "Объем экспорта",
    investmentDesc: "Общий объем капиталовложений компании на российском рынке",
    revenueDesc: "Общий годовой доход от деятельности компании в России",
    importDesc: "Общая стоимость товаров и услуг, импортируемых компанией в Россию",
    exportDesc: "Общая стоимость товаров и услуг, экспортируемых компанией из России",
    noData: "Данные отсутствуют",
  },
}

export function CompanyFinancials({
  investment,
  revenue,
  importVolume,
  exportVolume,
  language = "en",
}: CompanyFinancialsProps) {
  const t = translations[language]

  // Format currency with appropriate symbol
  const formatFinancialValue = (value?: number) => {
    if (value === undefined) return t.noData
    return formatCurrency(value, "USD")
  }

  return (
    <TooltipProvider delayDuration={300}>
      <Card className="mt-6 dark:bg-gray-800 dark:border-gray-700">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <DollarSign className="h-5 w-5" />
            {t.financials}
          </CardTitle>
        </CardHeader>
        <CardContent className="grid gap-4 sm:grid-cols-2">
          {/* Investment in Russia */}
          <div className="rounded-lg border border-gray-100 bg-gray-50 p-4 dark:border-gray-700 dark:bg-gray-800/50">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <TrendingUp className="h-4 w-4 text-gray-500" />
                <span className="text-sm font-medium text-gray-600 dark:text-gray-300">{t.investment}</span>
                <Tooltip>
                  <TooltipTrigger asChild>
                    <HelpCircle className="h-3.5 w-3.5 text-gray-400 cursor-help" />
                  </TooltipTrigger>
                  <TooltipContent className="max-w-xs">
                    <p>{t.investmentDesc}</p>
                  </TooltipContent>
                </Tooltip>
              </div>
            </div>
            <div className="mt-2 font-mono text-xl font-semibold dark:text-gray-200">
              {formatFinancialValue(investment)}
            </div>
          </div>

          {/* Revenue */}
          <div className="rounded-lg border border-gray-100 bg-gray-50 p-4 dark:border-gray-700 dark:bg-gray-800/50">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <DollarSign className="h-4 w-4 text-gray-500" />
                <span className="text-sm font-medium text-gray-600 dark:text-gray-300">{t.revenue}</span>
                <Tooltip>
                  <TooltipTrigger asChild>
                    <HelpCircle className="h-3.5 w-3.5 text-gray-400 cursor-help" />
                  </TooltipTrigger>
                  <TooltipContent className="max-w-xs">
                    <p>{t.revenueDesc}</p>
                  </TooltipContent>
                </Tooltip>
              </div>
            </div>
            <div className="mt-2 font-mono text-xl font-semibold dark:text-gray-200">
              {formatFinancialValue(revenue)}
            </div>
          </div>

          {/* Import Volume */}
          <div className="rounded-lg border border-gray-100 bg-gray-50 p-4 dark:border-gray-700 dark:bg-gray-800/50">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <ArrowDownRight className="h-4 w-4 text-gray-500" />
                <span className="text-sm font-medium text-gray-600 dark:text-gray-300">{t.importVolume}</span>
                <Tooltip>
                  <TooltipTrigger asChild>
                    <HelpCircle className="h-3.5 w-3.5 text-gray-400 cursor-help" />
                  </TooltipTrigger>
                  <TooltipContent className="max-w-xs">
                    <p>{t.importDesc}</p>
                  </TooltipContent>
                </Tooltip>
              </div>
            </div>
            <div className="mt-2 font-mono text-xl font-semibold dark:text-gray-200">
              {formatFinancialValue(importVolume)}
            </div>
          </div>

          {/* Export Volume */}
          <div className="rounded-lg border border-gray-100 bg-gray-50 p-4 dark:border-gray-700 dark:bg-gray-800/50">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <ArrowUpRight className="h-4 w-4 text-gray-500" />
                <span className="text-sm font-medium text-gray-600 dark:text-gray-300">{t.exportVolume}</span>
                <Tooltip>
                  <TooltipTrigger asChild>
                    <HelpCircle className="h-3.5 w-3.5 text-gray-400 cursor-help" />
                  </TooltipTrigger>
                  <TooltipContent className="max-w-xs">
                    <p>{t.exportDesc}</p>
                  </TooltipContent>
                </Tooltip>
              </div>
            </div>
            <div className="mt-2 font-mono text-xl font-semibold dark:text-gray-200">
              {formatFinancialValue(exportVolume)}
            </div>
          </div>
        </CardContent>
      </Card>
    </TooltipProvider>
  )
}

